#!/bin/bash

path=('/home/joe/Program/Python/Micheal/*.crt' '/home/joe/ca.crt')
while read host
do
    ssh joe@"$host"
    for i in ${path[@]}
        {
            ls -1 $i &> /dev/null
            if (( $? == 0 ))
            then
                out=$(openssl x509 -subject -issuer -noout -startdate -enddate -in $i)
                arry=("$(echo $out | grep -o "CN.*" | egrep -o "(CN=.*\sis|suer.*notB|efore.*notA|fter.*$)")")
                echo $arry | sed -r "s/CN=(.*)\sis.*(OU.*notB)\sefore=(.*notA)\sfter=(.*$)/\1\n\2\n\3\n\4\n/g" | sed -r "s/not(B|A)//g"
            fi

        }
    done < h.txt
